language: objective-c
osx_image: xcode8.2
xcode_project: Sample Project/SimpleLineChart.xcodeproj
xcode_scheme: SimpleLineChartTests
xcode_sdk: iphonesimulator
script:
  - xcodebuild clean build test -project "Sample Project/SimpleLineChart.xcodeproj" -scheme SimpleLineChartTests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7" ONLY_ACTIVE_ARCH=NO 
